// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package output

import (
	"fmt"
	"strings"
	"time"

	"github.com/siderolabs/kres/internal/version"
)

// PreambleTimestamp marks the time files are generated.
var PreambleTimestamp time.Time

// PreambleCreator is the name of the program.
var PreambleCreator string

// PreambleMarker is the current kres-specific marker line included in every
// file preamble produced by [Preamble]. It contains "BY KRES" so it cannot
// be confused with the generic "automatically generated" header used by
// other code generators.
const PreambleMarker = "THIS FILE WAS AUTOMATICALLY GENERATED BY KRES, PLEASE DO NOT EDIT."

// PreambleLegacyMarker is the marker line used by kres releases prior to the
// introduction of [PreambleMarker]. The line text alone is not unique to
// kres (it matches output from many code generators), so callers using it
// for detection must combine it with an additional kres-specific check
// (typically the " by kres " generator tag emitted on the line below).
const PreambleLegacyMarker = "THIS FILE WAS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT."

// PreambleCreatorTag is a substring present in every kres-generated preamble
// on the "Generated on ... by kres <tag>." line. It is the most reliable
// kres-only marker because the "kres" generator name is baked in at build
// time via [version.Name].
const PreambleCreatorTag = " by kres "

// Preamble returns file auto-generated preamble with specified comment character.
func Preamble(commentPrefix string) string {
	const preamble = `
` + PreambleMarker + `

Generated on %s by %s.
`

	if PreambleTimestamp.IsZero() {
		PreambleTimestamp = time.Now().UTC()
	}

	if PreambleCreator == "" {
		PreambleCreator = version.Name + " " + version.Tag
	}

	preambleStr := fmt.Sprintf(preamble, PreambleTimestamp.Format(time.RFC3339), PreambleCreator)

	byLines := strings.Split(strings.TrimSpace(preambleStr), "\n")

	for i := range byLines {
		byLines[i] = strings.TrimSpace(commentPrefix + byLines[i])
	}

	return strings.Join(byLines, "\n") + "\n\n"
}

// License returns file auto-generated license.
func License(license, commentPrefix string) string {
	byLines := strings.Split(strings.TrimSpace(license), "\n")
	for i := range byLines {
		byLines[i] = strings.TrimSpace(commentPrefix + byLines[i])
	}

	return strings.Join(byLines, "\n") + "\n"
}
