name: default
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request: {}
env:
  CI_ARGS: --cache-from=type=registry,ref=registry.dev.siderolabs.io/${GITHUB_REPOSITORY}:buildcache --cache-to=type=registry,ref=registry.dev.siderolabs.io/${GITHUB_REPOSITORY}:buildcache,mode=max
jobs:
  default:
    permissions:
      contents: write
      packages: write
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Unshallow
        run: |
          git fetch --prune --unshallow
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          config-inline: |
            [worker.oci]
              gc = true
              gckeepstorage = 100000 # 100 GiB

              [[worker.oci.gcpolicy]]
                keepBytes = 32212254720 # 30 GiB
                keepDuration = 604800
                filters = [ "type==source.local", "type==exec.cachemount", "type==source.git.checkout"]
              [[worker.oci.gcpolicy]]
                all = true
                keepBytes = 107374182400 # 100 GiB